### ISSUE TITLE
uneven batches causes crash when loading data

### ISSUE THREAD

**Issue by dllussier** [courtois-neuromod/dypac#62]
With 1050 subjects and n_batches=5 or 10:

`[MultiNiftiMasker.fit] Loading data from [../data/func/fmri_sub0050002_session1_run1_n.nii.gz, ../data/func/fmri_sub0050003_session1_run1_n.nii.gz, ../data/func/fmri_sub0050004_session1_run1_n.nii.gz, ../data/func/fmri_sub0050005_session1_ru
[MultiNiftiMasker.fit] Computing mask
Traceback (most recent call last):
  File "dypac_abide_sub50bat5.py", line 48, in <module>
    model.fit(func, confounds=conf)
  File "/lustre03/project/6003287/dlussier/myenv/lib/python3.6/site-packages/dypac-0.3-py3.6.egg/dypac.py", line 248, in fit
  File "/lustre03/project/6003287/dlussier/myenv/lib/python3.6/site-packages/nilearn/input_data/multi_nifti_masker.py", line 208, in fit
    **mask_args)
  File "/lustre03/project/6003287/dlussier/myenv/lib/python3.6/site-packages/joblib/memory.py", line 355, in __call__
    return self.func(*args, **kwargs)
  File "/lustre03/project/6003287/dlussier/myenv/lib/python3.6/site-packages/nilearn/masking.py", line 369, in compute_multi_epi_mask
    for epi_img in epi_imgs)
  File "/lustre03/project/6003287/dlussier/myenv/lib/python3.6/site-packages/joblib/parallel.py", line 1007, in __call__
    while self.dispatch_one_batch(iterator):
  File "/lustre03/project/6003287/dlussier/myenv/lib/python3.6/site-packages/joblib/parallel.py", line 835, in dispatch_one_batch
    self._dispatch(tasks)
  File "/lustre03/project/6003287/dlussier/myenv/lib/python3.6/site-packages/joblib/parallel.py", line 754, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/lustre03/project/6003287/dlussier/myenv/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 209, in apply_async
    result = ImmediateResult(func)
  File "/lustre03/project/6003287/dlussier/myenv/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 590, in __init__
    self.results = batch()
  File "/lustre03/project/6003287/dlussier/myenv/lib/python3.6/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/lustre03/project/6003287/dlussier/myenv/lib/python3.6/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/lustre03/project/6003287/dlussier/myenv/lib/python3.6/site-packages/nilearn/masking.py", line 266, in compute_epi_mask
    smooth=(1 if opening else False))
  File "/lustre03/project/6003287/dlussier/myenv/lib/python3.6/site-packages/joblib/memory.py", line 355, in __call__
    return self.func(*args, **kwargs)
  File "/lustre03/project/6003287/dlussier/myenv/lib/python3.6/site-packages/nilearn/image/image.py", line 450, in _compute_mean
    imgs = check_niimg(imgs)
  File "/lustre03/project/6003287/dlussier/myenv/lib/python3.6/site-packages/nilearn/_utils/niimg_conversions.py", line 263, in check_niimg
    niimg = load_niimg(niimg, dtype=dtype)
  File "/lustre03/project/6003287/dlussier/myenv/lib/python3.6/site-packages/nilearn/_utils/niimg.py", line 127, in load_niimg
    dtype = _get_target_dtype(_get_data(niimg).dtype, dtype)
  File "/lustre03/project/6003287/dlussier/myenv/lib/python3.6/site-packages/nilearn/_utils/niimg.py", line 23, in _get_data
    data = np.asanyarray(img._dataobj)
  File "/lustre03/project/6003287/dlussier/myenv/lib/python3.6/site-packages/numpy/core/_asarray.py", line 138, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/lustre03/project/6003287/dlussier/myenv/lib/python3.6/site-packages/nibabel/arrayproxy.py", line 393, in __array__
    arr = self._get_scaled(dtype=dtype, slicer=())
  File "/lustre03/project/6003287/dlussier/myenv/lib/python3.6/site-packages/nibabel/arrayproxy.py", line 360, in _get_scaled
    scaled = apply_read_scaling(self._get_unscaled(slicer=slicer), scl_slope, scl_inter)
  File "/lustre03/project/6003287/dlussier/myenv/lib/python3.6/site-packages/nibabel/arrayproxy.py", line 339, in _get_unscaled
    mmap=self._mmap)
  File "/lustre03/project/6003287/dlussier/myenv/lib/python3.6/site-packages/nibabel/volumeutils.py", line 523, in array_from_file
    n_read = infile.readinto(data_bytes)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/gzip.py", line 482, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
Tue Apr 21 15:25:52 EDT 2020`

Error corrected by removing 50 subjects so that n_batches was divisible by number of subjects with no remainder

**Comment by dllussier** [comment]
Error occurs on HPC but does not replicate locally. Investigating further with the HPC.
